
### home
GET http://localhost:8000

# //----------------------- partie tomes

### get all tomes
GET http://localhost:8000/api/tomes


### get 1 tomes from id
GET http://localhost:8000/api/tomes/5

# //----------------------- partie colection

### get all colection
GET http://localhost:8000/api/collection


### get all serie in colection by user id
GET http://localhost:8000/api/collection/serie_collection/1

### get all serie not in colection by user id
GET http://localhost:8000/api/collection/serie_notin_collection/1


### get all tome by serie for a user (a retravailler)
GET http://localhost:8000/api/collection/alltomes_collection/1/4

# ### get all tome in colection for a user (a retravailler)
# GET http://localhost:8000/api/collection/tome_collection/2"

### post a new tome in a serie for user's colection
POST http://localhost:8000/api/collection/tome_collection_add/


# //----------------------- partie series

### get all series
GET http://localhost:8000/api/series

### get all tomes in a serie
GET http://localhost:8000/api/series/alltomes_serie/2

# //----------------------- partie lectures


### get all lectures
GET http://localhost:8000/api/lecture


### GET all lectures by user id 
GET http://localhost:8000/api/lecture/tome_lecture/3

###  GET all series in lectures by user id
GET http://localhost:8000/api/lecture/series_lecture/3

### get all tome from a serie in a lecture by user id 
GET http://localhost:8000/api/lecture/tomes_in_serie

# ### get 1 movie from id
# GET http://localhost:8000/api/movies/3

# ### POST movie
# POST http://localhost:8000/api/movies/post
# Content-Type: application/json

# {
#     "id" : "13",
#     "title": ",nouveau test",
#     "director": "michel",
#     "year": "1100",
#     "color": "1",
#     "duration": "3"
# }

# ### PUT movie
# PUT http://localhost:8000/api/movies/3/update
# Content-Type: application/json

# {
#     "title": "Ceci est notre nouveau titre",
#     "year": 1991
    
# }

# ### DELETE movie
# DELETE http://localhost:8000/api/movies/13



# //----------------------- partie playliste

# ### get playlist listes
# GET http://localhost:8000/api/playlists

# ### GET 1 movie from id
# GET http://localhost:8000/api/playlists/1

# ### POST playliste
# POST http://localhost:8000/api/playlists/post
# Content-Type: application/json

# {
#     "genre" :"playliste a suprimer",
#     "name" : "playliste a suprimer"
# }

# ### PUT playliste
# PUT http://localhost:8000/api/playlists/1/update
# Content-Type: application/json

# {
#     "genre" :"filme de guerre",
#     "name" : "mes pref"
# }

# ### DELETE playliste
# DELETE http://localhost:8000/api/playlists/6

# //---------------------------------partie movie_playlist

# ### trouver les films liés a une playlist en fonction de l'id de la playliste
# GET http://localhost:8000/api/movie_playlist/2

# ### créer une nouvelle liaison entre un film et une playliste
# POST http://localhost:8000/api/movie_playlist/post
# Content-Type: application/json

# {
#     "movie_id" :"2",
#     "playlist_id" : "2"
# }
